language: node_js
node_js:
  - 10

install: npm install

script:
  - npm run build

cache:
  yarn: true
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  fqdn: better-call.dev
  on:
    branch: master
