language: node_js
node_js:
  - 10

install: npm install

script:
  - npm run lint
  - npm run build

cache:
  yarn: true
  directories:
    - "node_modules"

before_deploy:
  - cp dist/index.html dist/404.html
  - "sed -i \"1i---\\npermalink: /404.html\\n---\" dist/404.html"

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  fqdn: baking-bad.github.io/better-call-dev
  on:
    branch: master
